jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

language: clojure
lein: lein2
script: lein do clean, cljsbuild once main-dev, cljsbuild once ui-dev, clean, cljsbuild once main-release, cljsbuild once ui-release
